### ISSUE TITLE
Open gate window too small

### ISSUE THREAD

**Issue by l3gitpanda** [nguyenvanduocit/obsidian-open-gate#1]
https://i.imgur.com/0SjGHYD.png
https://i.imgur.com/aHFqpY7.png

Hey so I tried this with wikipedia and chatGPT and the window is wayyy too small and i cant even see responses from GPT, specifically in the vertical direction. Is there something im doing wrong or is this a bug? I'd love to use this awesome plugin once this issue is fixed/worked out! Thanks for the great plugin idea!

**Comment by nguyenvanduocit** [comment]
This is a bug, have you used the latest version, what operating system are you using?

**Comment by nguyenvanduocit** [comment]
Can you please contack me via discord, I will take closer look on your case: duocnguyen#2871
