### ISSUE TITLE
Cannot sign in with google for chatgpt

### ISSUE THREAD

**Issue by brycepg** [nguyenvanduocit/obsidian-open-gate#15]
"Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in."

I tried changing the browser agent to no avail. using fedora

**Comment by nguyenvanduocit** [comment]
look like OpenAI add more security protect. haizzz

**Comment by brycepg** [comment]
It was actually google sign in that wasn't working. Do you sign in without google?

**Comment by brycepg** [comment]
It's working today, strange

**Comment by nguyenvanduocit** [comment]
it's ok, haha, strange is software develoment's purpose
