### ISSUE TITLE
Thank you very much! Provide such a great extension 😜

### ISSUE THREAD

**Issue by zhouxinghong** [nguyenvanduocit/obsidian-open-gate#17]
Thank you very much! Provide such a great extension 😜

But found several problems in use:

Question 1:
Server resources of some Japanese websites, such as images and videos, cannot be parsed. Hope that troubleshoots the issue and fixes it in time.
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/54253524/b671d0ad-2667-4252-8215-c5dcf496cc61)

Question 2:
by the following way
```gate
https://www.youtube.com
height: 300
```
```
![height:800px](https://www.youtube.com)
```
```
![height:800px;profile:account-1](https://www.youtube.com)
```

How can I customize the display style of the embedded webpage?
For example: I want to make the embedded webpage look rounded, just like the following performance
Embedded web pages display rounded corner styles
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/54253524/ce6ec6ac-bc82-47be-b7c9-bafca511c3ef)
The current embedded page display style is as follows:
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/54253524/87035018-0ef3-4a59-ba1e-32949376602c)

Question 3:
Use the following syntax:
```
![height:800px](https://12bit.vn/)
```
```
![height:800px](https://www.youtube.com/)
```
```
![height:800px;profile:account-1](https://www.youtube.com/)
```
An error will appear in the editor:
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/54253524/43bab44a-cb51-496e-a7b5-9c093266b8a1)

The latest version: 1.81
Obsidian: 1.35

**Comment by zhouxinghong** [comment]
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/54253524/865d4536-f36b-4d74-a0ee-573e4eb21f7c)

**Comment by zhouxinghong** [comment]
All web page styles and image resources failed to load. . . 😂

**Comment by nguyenvanduocit** [comment]
1) look like we have a big trouble with Japan website. I think this issue should be resolve by VPN, and some website prevent tobe embedded. In this case, 3rd party service should be used, like hidemyass.com. I can not fix that issue from the plugin.
2) It's a good idea, I will find a way to allow you to custom CSS 
3) it's normal behaviour, because I override the default behaviour of the editor. I will try to fix it

**Comment by zhouxinghong** [comment]
Previously in version 1.30 there was also a problem with Japanese website images not loading, but later you fixed this problem.

**Comment by zhouxinghong** [comment]
There are actually a few more features that need to be added for this plugin to work fully, so I'll sort it out and send it to you later. Thank you for providing such an excellent plugin.

**Comment by nguyenvanduocit** [comment]
about the Japan website. Do you remember what is the solution? I just added support for useragent:

![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/1256953/aa344917-cb7b-4ffe-9e24-aa6fb6817a4f)

**Comment by zhouxinghong** [comment]
https://github.com/nguyenvanduocit/obsidian-open-gate/issues/8
You can compare the code of 1.3.3. This version solves the problem that the image resources of the Japanese website cannot be loaded. Then compare it with 1.8.1 to see which key codes are overwritten or lost.

**Comment by zhouxinghong** [comment]
A good reference to the 1.3.3 code will definitely solve this problem😜👍

**Comment by zhouxinghong** [comment]
> about the Japan website. Do you remember what is the solution? I just added support for useragent:
> 
> ![image](https://user-images.githubusercontent.com/1256953/245355295-aa344917-cb7b-4ffe-9e24-aa6fb6817a4f.png)

The following syntaxes are not supported. . .
`
![height:800px](https://www.youtube.com)
`

**Comment by nguyenvanduocit** [comment]
it's really complicated to support these parrams in short syntax.

**Comment by zhouxinghong** [comment]
I think it should be possible to change the following line
`
useragent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, comme Gecko) Chrome/113.0.0.0 Safari/537.36
`
Write it into the JS function and call it!

**Comment by zhouxinghong** [comment]
I am not sure
`![height:800px](https://www.youtube.com/)`
How does this syntax work.

**Comment by zhouxinghong** [comment]
Don't worry, think about it slowly, you should come up with an ideal solution:

The console gives the following error:
to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin
R_BLOCKED_BY_RESPONSE. NotSameOrigin 403
These should be the main reasons why Japanese website images and website style resources cannot be loaded!

**Comment by zhouxinghong** [comment]
There should be no use of the following line
`
useragent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
`
way to solve the current problems.
