### ISSUE TITLE
When click on link that need to open in new windows, Open Gate no respond.

### ISSUE THREAD

**Issue by iris2jane** [nguyenvanduocit/obsidian-open-gate#2]
A great plugin! 
However, it seems that it is impossible to open the link that needs to open a new window. 
Clicking such a link does not respond.

**Comment by duocnv-firegroup** [comment]
hum, look like it's a limit of webview, let's me fix it./

**Comment by nguyenvanduocit** [comment]
Look like the I have to add new event listener to open the site in new tag

**Comment by rk1a** [comment]
It would also be useful to have an option that allows to open links in the external browser.

**Comment by nguyenvanduocit** [comment]
improved in the latest version
