### ISSUE TITLE
link syntax does not show in preview mode

### ISSUE THREAD

**Issue by ksdavidc** [nguyenvanduocit/obsidian-open-gate#20]
link syntax
`![height:800px](https://12bit.vn)`

does not show in preview mode. I wish it would.

**Comment by nguyenvanduocit** [comment]
The new version should work, sorry for late reply

**Comment by MelodyDuplaix** [comment]
I've just installed open gate, and I think I have the same problem. Whether in read mode or live preview, and no matter which syntax I try, the link syntax doesn't display anything.
like this : `![height:800px](https://12bit.vn)`
show this:
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/131142776/3d450ffe-8229-4c00-ae35-3af5518f7c27)
