### ISSUE TITLE
Embed lokal html File

### ISSUE THREAD

**Issue by JakobFerdinand** [nguyenvanduocit/obsidian-open-gate#21]
Hello,

First of all that is a great extension! Thank you!

Is it possible to embed a local `html` file?
I tried different ways:
```
homepage.html
```
or 
```
.\homepage.html
```

also the inline versions, but it always displayed an empty area.

Thank you for your help!

**Comment by nguyenvanduocit** [comment]
you can try to use the local file protocol like: file://abs_path/to_your_file.html

**Comment by andrewmcgivery** [comment]
See: https://github.com/nguyenvanduocit/obsidian-open-gate/issues/24

Should close this as duplicate. :)
