### ISSUE TITLE
It is creating problem for other note's content

### ISSUE THREAD

**Issue by Gourav1910** [nguyenvanduocit/obsidian-open-gate#22]
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/101202140/b44bc6d9-75e2-4ef9-80c2-e9946184eb69)

Hi, I copy pasted my chatgpt conversation in obsidian note and because of open gate plugin in reading mode it is showing weird behaviour by leaving lot of space and keeping the image in center. I turned on and off various plugins and when I turned off open gate plugin after that it resolved the problem. So please correct this problem🙏. Thanks.

**Comment by nguyenvanduocit** [comment]
it's because of new embed format, Maybe I will have to make some change

**Comment by nguyenvanduocit** [comment]
The new version was fixed this issue
