### ISSUE TITLE
Unable to sign in with Google

### ISSUE THREAD

**Issue by Myradose** [nguyenvanduocit/obsidian-open-gate#23]
I am unable to sign in with google for all embeded websites. Usually this isn't a problem since you can usually set a password using "Forgot password" for almost every site, but unfortunately ChatGPT doesn't allow you to set a password if you originally signed in with Google. When trying to log in, I get the message "This browser or app may not be secure.". After looking this up, it seems like the only way to resolve this is to turn on "Less secure app access" in the [Google settings](https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4MwmBOrYwoJGuV74BL2bg123CqXJhXPjhb1D6_HT-5NGaUMV2q-qtjJtirYSWTK8z_m_SkRAnodFhZgy0pnuWiw0o0dgQ) but to do this, you have to turn off 2FA which I'm not interested in doing.

**Comment by kaem-e** [comment]
yeah same here, im guessing theres a way to add something in the custom user agent options to change this probably but i dont really know how ![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/46230985/e832b418-7c56-4bca-8fe6-993ac57aebcc)

**Comment by SunkenInTime** [comment]
I have the same problem!

**Comment by nguyenvanduocit** [comment]
sorry guys, I just back from a vocation, I will update to you guy soon.

**Comment by warshell** [comment]
++ same problem

**Comment by jasir** [comment]
Change user agent to firefox, works for me!

"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0";

**Comment by warshell** [comment]
> Change user agent to firefox, works for me!
> 
> "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0";

Incredible, Saver! I've tried numerous user agents, and yours is the one that actually worked. Thank you!

**Comment by nguyenvanduocit** [comment]
Thanks you and your PR is merged, Will be released soon

**Comment by miztizm** [comment]
Can someone confirm that this user agent dosent work anymore? 

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0`

and this one work? 

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0/HBpt3US8-18`

Thanks
