### ISSUE TITLE
Support for Local HTML files

### ISSUE THREAD

**Issue by Aetherinox** [nguyenvanduocit/obsidian-open-gate#24]
I love this plugin. The only thing I'd love to see is support for local files.

I've tried about 6 different ways to call a local HTML + CSS file I've added to my vault, and they all show as a blank page unfortunately.
This would help with me being able to keep a tool with me, without the need to worry about a website having to host the tool.

**Comment by nguyenvanduocit** [comment]
did you try to use local file protocol like this: file://pathtoyourfile

**Comment by Aetherinox** [comment]
I've tried a few ways of linking directly to the file, something along the files of

````
```gate
file://test.txt
```
````

I've also tried the absolute direct path to the file using the full drive + path.

Also tried `//` and `\\` to escape the first slash. The only result I get is a blank `<body></body>` tag when I use inspect element.

**Comment by andrewmcgivery** [comment]
Tested this locally and local HTML file are working as expected in 1 different formats:

![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/4482878/e010d145-f926-4f8f-a82e-5b9a06bd112d)

![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/4482878/819f6747-13c6-4087-a6bc-c99f10e2d885)

@Aetherinox Can you try to see if either of these approaches work for you with the latest version of Open Gate?

@nguyenvanduocit The takeaway here may just be a note in the README about referencing local files.

**Comment by nguyenvanduocit** [comment]
File protocol works well on macos but the absolute path. I think it's safe to write about the file protocol.

@Aetherinox Reopen the issue if you still have the issue
