### ISSUE TITLE
Feature request: create and open a open gate using frontmatter

### ISSUE THREAD

**Issue by machado-t** [nguyenvanduocit/obsidian-open-gate#25]
Please see identical request in similar plugin:

https://github.com/Ellpeck/ObsidianCustomFrames/issues/89

**Comment by nguyenvanduocit** [comment]
I have an idea to create a feature that, when you click on any link in your notes, the link will be opened as a new gate instead of the default browser, preventing you from being navigated outside of Obsidian.

**Comment by nguyenvanduocit** [comment]
This feature was merged into main, but please wait for the next release, we are do some adjustment.
