### ISSUE TITLE
how to custom css in code blocks?

### ISSUE THREAD

**Issue by up2young** [nguyenvanduocit/obsidian-open-gate#26]
can I custom css in a block?
```gate  
https://12bit.vn
height:300
css?
```

**Comment by nguyenvanduocit** [comment]
Currenty, no way to do this, I will ad tag need-help on your issue

**Comment by andrewmcgivery** [comment]
Submitted a PR for this cause I need this too! :) 

````markdown
```gate
https://12bit.vn
height:300
css: |
   html { filter: invert(90%) hue-rotate(180deg)!important; }
```
````

**Comment by nguyenvanduocit** [comment]
Really cool

**Comment by nguyenvanduocit** [comment]
You code is very good, I merged it into the codebase, and then I just make some change, I will move the inject css code in to the function createWebviewTag.

**Comment by nguyenvanduocit** [comment]
Do you have a Discord username on the Obsidian server, so that I can mention you in the update announcement?

**Comment by andrewmcgivery** [comment]
> Do you have a Discord username on the Obsidian server, so that I can mention you in the update announcement?

I don't but if possible, you can just refer to my github username. :)

**Comment by nguyenvanduocit** [comment]
sure
