### ISSUE TITLE
This works really well - AND - anyway to stay signed in on sites???

### ISSUE THREAD

**Issue by johnsonblue75** [nguyenvanduocit/obsidian-open-gate#3]
Hey, great job here. This plugin works super well and much better than the alternatives. I am using it specifically with Miro and with some applications built on Google Sheets and a few other things.

Is there anyway to stay signed in??? So whenever I go to open something it always prompts me to re-sign in. I guess the cookies stored in my browser (Chrome/Vivaldi) don't "talk to" obsidian/obsidian plugins.

This feature - if possible - would be amazing. 

Thanks for your great work!

**Comment by nguyenvanduocit** [comment]
It's a bit weird, but I have to say it works fine on my machine, in the code I intentionally used a key to store cookies. If you don't mind, connect with me via Discord. I will take a closer look: duocnguyen#2871

**Comment by johnsonblue75** [comment]
Hey, it does work. Wow - I wanted to post here so others would see that I was wrong above. Brilliant plugin even better. :-) I'm still going to reach out on discord.

**Comment by nguyenvanduocit** [comment]
ah, to correct that, Obsidian can not access browser cookie, so that you still have to login again in obsidian, but only for the first time you add new gate.
