### ISSUE TITLE
Can't sign in to Google

### ISSUE THREAD

**Issue by joshuadanpeterson** [nguyenvanduocit/obsidian-open-gate#30]
I recently downloaded this plugin after watching this video: [https://youtu.be/iJ0-u4KlGyQ?si=wQZ1xv78Od3ONJw3](https://youtu.be/iJ0-u4KlGyQ?si=wQZ1xv78Od3ONJw3) and tried to sign in to Google but it won't let me. I just get a "Couldn't sign you in" message saying the app may not be secure. Any ideas on how to fix this?

![PXL_20231017_181315047.jpg](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/6033094/d730b9e4-122a-4d56-9ceb-1d132128224b)

**Comment by rzfzr** [comment]
I just downloaded this and found the same problem.

I found the answer in issue #23, change the user agent to the following:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0/HBpt3US8-18
```
Searching for closed issues is valuable 👍

**Comment by nguyenvanduocit** [comment]
Thanks for point out the solution. Maybe I should set it as default agent

**Comment by joshuadanpeterson** [comment]
Thanks @rzfzr. I'll try that now

**Comment by joshuadanpeterson** [comment]
@rzfzr That worked. Thank you.
