### ISSUE TITLE
Hotkeys being robbed by the browser instance instead of going to obsidian.

### ISSUE THREAD

**Issue by rzfzr** [nguyenvanduocit/obsidian-open-gate#31]
I'm having the following issue when an open gate has focus.
I have some hotkeys like F1 and F2 setup (without modifiers), and these keys do absolutely nothing, also ctrl+w is setup to close the open tab, it also only works after I click the sidebar.

**Comment by nguyenvanduocit** [comment]
I think it is normal behavior. Because when the frame has focus, it should handle the hotkey itself.

**Comment by rzfzr** [comment]
This could be an option, do you have any idea on how to implement the passthrough? I could do a PR.
