### ISSUE TITLE
Google Account Sign-In isn’t working with Obsidian Open Gate Plugin

### ISSUE THREAD

**Issue by bauche25** [nguyenvanduocit/obsidian-open-gate#32]
Hello,

This is a great plugin! So glad you made it. I am having a problem with Google Apps and signing-in through the plugin for Google App gates. Other users are experiencing this issue too: https://forum.obsidian.md/t/google-account-sign-in-isnt-working-with-open-gate-plugin/65760

Can you resolve this in the next update?

Thank you so much,
John

**Comment by nguyenvanduocit** [comment]
Please use the following user agent: 

![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/1256953/47c02e46-9b5b-4417-a7e3-2097194f7cc9)

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0/HBpt3US8-18
```
