### ISSUE TITLE
Too long url removes the edit button

### ISSUE THREAD

**Issue by Osigmae** [nguyenvanduocit/obsidian-open-gate#33]
Too long url pushes the edit button to far to the right to be visible.
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/58618877/e2994a16-a335-4adf-aaad-800567599eeb)

**Comment by nguyenvanduocit** [comment]
Good issue. I think this issue can arise quite easily.

**Comment by nguyenvanduocit** [comment]
Fixed in version 1.9.3
