### ISSUE TITLE
Better explanation for manual icons

### ISSUE THREAD

**Issue by Osigmae** [nguyenvanduocit/obsidian-open-gate#34]
How to add a manual icon is not well explained, and it would be nice if I could reference a local svg or icon pack in my obsidian directly instead of pasting an URL to the web.

**Comment by nguyenvanduocit** [comment]
At the beginning, I think every website should have its own icon, so I try to fetch it from its website. But I can make it a little bit more advanced by allowing you to use your own icons.

**Comment by nguyenvanduocit** [comment]
you can use icon on your icon pack by just put the name on it, like "globe"
