### ISSUE TITLE
Login issue on iPad

### ISSUE THREAD

**Issue by alx-xlx** [nguyenvanduocit/obsidian-open-gate#35]
The plugin works very well on the desktop version for chat.openai.com
However when I try to Login to chat.openai.com then the page just refreshes without showing any login screen.

**Comment by nguyenvanduocit** [comment]
On mobile, Obsidian users encounter a completely different core platform compared to the desktop version, necessitating the use of iframes on iPads and mobile devices. However, iframes are not supported by a significant number of websites.
