### ISSUE TITLE
Sending double links to browser

### ISSUE THREAD

**Issue by hwindee** [nguyenvanduocit/obsidian-open-gate#38]
Hello! Thank you for the plugin, it's amazing! But I have strange issue. I embedded several websites into obsidian via open gate. When I click links on them, it opens double tab in browser, instead of one. How can that be fixed?... 

https://github.com/nguyenvanduocit/obsidian-open-gate/assets/96774084/6f15c6d5-d64e-44d3-a9bf-5e607a565f8f

**Comment by nguyenvanduocit** [comment]
Sorry for the issue, it is a bug on the plugin. I will fit it soon.

**Comment by nguyenvanduocit** [comment]
Version 1.9.8 is out, the issue should be fixed. Reopen the issue if you still have the same issue.
