### ISSUE TITLE
Feature Request: Option to refresh website

### ISSUE THREAD

**Issue by Zebrazilla** [nguyenvanduocit/obsidian-open-gate#4]
Using this with ChatGPT the session sometimes gets stale in some way, shape or form, where the "gate" needs to be closed and opened again in order to restart the session.

I think it would be nice to see the added option of "Refresh tab" in the "More options" menu of a tab with a "gate" open in it.

**Comment by nguyenvanduocit** [comment]
Added in version 1.1.0. Just released

**Comment by nguyenvanduocit** [comment]
Now you can right click on the tab icon. You can see the refresh option.

**Comment by Zebrazilla** [comment]
I've been using the feature for a while now and it works perfectly! Thank you for the swift implementation!
