### ISSUE TITLE
Hello! Can this extension be ported to the VSCode environment for use?

### ISSUE THREAD

**Issue by zhouxinghong** [nguyenvanduocit/obsidian-open-gate#45]
Hello! Can this extension be ported to the VSCode environment for use?

**Comment by zhouxinghong** [comment]
If you can use this extension in VSCode, the effect will be more ideal than Obsidian.

**Comment by zhouxinghong** [comment]
Because VSCode itself has IDE characteristics.

**Comment by nguyenvanduocit** [comment]
I can not port this plugin into VS Code. it's out of scope. Sorry for that
