### ISSUE TITLE
Bug: Gate Links should open in correct leaf

### ISSUE THREAD

**Issue by andrewmcgivery** [nguyenvanduocit/obsidian-open-gate#48]
https://github.com/nguyenvanduocit/obsidian-open-gate/blob/main/src/main.ts#L187

**Bug:** 

This line does not pass in the gate's position when a gate is matched on title. The result is that it opens up in wrong spot in the UI (defaults to the right side).

**Desired Behaviour:**

Opening a gate via a link should open in the position configured in the gate settings.

**Solution:**

Pass the gate position into the call to openView.

**Comment by nguyenvanduocit** [comment]
Thank you, fixed in master
