### ISSUE TITLE
modification ability

### ISSUE THREAD

**Issue by r4nchy** [nguyenvanduocit/obsidian-open-gate#56]
I was using **https://chat.openai.com/** using opengate and then found that upon changing the size of the chatgpt windows, the way we give our query to the chatgpt changes.

Example When the chatgpt window is large such that the left sidebar is visible then using the ENTER key sends the reply.

on the other hand if the chatgpt window is small such that the left sidebar autohides itself then the ENTER key sends the cursor to the next line. And we have to manually send the reply by using mouse and clicking on the send button.

Does this extension allow any type of modification that will solve this ?

**Comment by nguyenvanduocit** [comment]
Hi, are you still use the plugin, I hope you still, in this case, please join this discord, we will talk about this deeper; https://discord.gg/rxCdQ2K8M5
