### ISSUE TITLE
cannot go through security check process

### ISSUE THREAD

**Issue by frankcsliu** [nguyenvanduocit/obsidian-open-gate#57]
I love this Obsidian add-on and would like to rank it as the most essential tool in my toolbox. Thank you for your outstanding contribution! 
I want to create a gate to Perplexity but cannot go through the security check. Please check this issue and help me through it. 

Thank you! 
![2024-01-24_08-58-05](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/12545793/fc55c4ed-2319-481b-9a0e-db1cbdc71c7c)

**Comment by bwnjnOEI** [comment]
same to Claude by login click "continue with google"

**Comment by frankcsliu** [comment]
Thank you but the security check page came before I could see the login page. Did I miss anything?

**Comment by wwjCMP** [comment]
I meet same issue

**Comment by dsqr84** [comment]
same for ChatGPT -> https://chat.openai.com/

Loops through the cloudflare verification

**Comment by nguyenvanduocit** [comment]
Let me check

**Comment by frankcsliu** [comment]
I searched for an alternative method to bypass the problem by using labs.perplexity.ai first before moving on to perplexity. See here. https://www.reddit.com/r/perplexity_ai/comments/16sj2tn/cloudflare_security_blocks_me_when_trying_to_use/ 
Hopefully, there will soon be an ideal solution for all other services.

**Comment by nguyenvanduocit** [comment]
Sorry for late response, just back from a very long vocation.

**Comment by dsqr84** [comment]
I can confirm it's working with ChatGPT now.

**Comment by nguyenvanduocit** [comment]
So if you guys still have this issue, please reopen

**Comment by frankcsliu** [comment]
Hi, I reencounter this issue of security check. Could you reopen this task and help investigate it?
