### ISSUE TITLE
Gate doesn't work

### ISSUE THREAD

**Issue by 4gotName** [nguyenvanduocit/obsidian-open-gate#59]
After the last update gate doesn't work in notes

![obsidian-gate](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/44590741/10c5e55f-0e72-47c1-a0b8-6fd938974483)

**Comment by Thylane** [comment]
Try adding `url: ` before the link. It works for me.
~~~
```gate
url: https://www.google.com/
height: 300
```
~~~

**Comment by 4gotName** [comment]
> Try adding `url: ` before the link. It works for me.
> 
> ```
> ```gate
> url: https://www.google.com/
> height: 300
> ```
> ```
Thx, this really works

**Comment by 4gotName** [comment]
> Try adding `url: ` before the link. It works for me.
> 
> ```gate
> url: https://www.google.com/
> height: 300
> ```
Thx, this really works

**Comment by ArthurSrz** [comment]
> Try adding `url: ` before the link. It works for me.
> 
> ```
> ```gate
> url: https://www.google.com/
> height: 300
> ```
> ```

Worked for me as well. Thanks !
