### ISSUE TITLE
Not able to get past veritifcation

### ISSUE THREAD

**Issue by KruznickMeta** [nguyenvanduocit/obsidian-open-gate#60]
Hi, 

I am unable to get past verification I've attached an image for clarification. It just keeps going back to verification.
<img width="640" alt="SCR-20240203-gyoc" src="https://github.com/nguyenvanduocit/obsidian-open-gate/assets/111281168/48ebbad4-f651-4931-b95d-1f48fb7c443e">

**Comment by nguyenvanduocit** [comment]
Sorry for late response, just back from a very long vocation.

**Comment by nguyenvanduocit** [comment]
Duplicate with #57
