### ISSUE TITLE
None of the code blocks rendering

### ISSUE THREAD

**Issue by Aetherinox** [nguyenvanduocit/obsidian-open-gate#62]
I noticed recently that none of the code blocks for the gate plugin are rendering.

Tried numerous different vaults, as well as a test vault with nothing but OpenGate installed. I probably have over 50 or so website previews integrated into my vaults, and every one of them just shows up blank.

Open Gate: v1.11.1
Obsidian: v1.5.3
OS: Windows 11 Pro

Went and tried the "Custom Frames" plugin just to test if a connection between Obsidian and a website could be done successfully, and that plugin works fine. I just don't prefer that plugin.

**Comment by nguyenvanduocit** [comment]
Can you try to use the new syntax:

```gate
url: https://12bit.vn
```

notice that we have `url`. Old syntax does not have this.

**Comment by Aetherinox** [comment]
Interesting, that worked. When the heck did that change. Normally I check the docs when an update is released, but somehow I missed that.

Appreciate it. Now I've got to go through the vault and change that.

**Comment by nguyenvanduocit** [comment]
Really sorry about this, in some early versions, I support the old syntax (without url), then I change to new syntax and keep support old syntax, but i think there are a bug. I will try to fix it.

**Comment by Aetherinox** [comment]
A bug in the zoom feature? Or do you mean supporting with and without the `url:` key, because that part really doesn't matter much. I don't mind adding `url`, in fact my vault already has the change.

But the `zoom` argument is what seems to be messed up right now. All pages are stuck at 100%.

**Comment by nguyenvanduocit** [comment]
make sense, updated

**Comment by Aetherinox** [comment]
Sorry, no idea how I missed this.

Yes, `zoomFactor` does work. Thanks a bunch.
