### ISSUE TITLE
Width doesn't adapt to setting "Readable line length"

### ISSUE THREAD

**Issue by dianedef** [nguyenvanduocit/obsidian-open-gate#63]
Thank you for this amazing plugin!

I use the setting "Readable line length" which is an official option inside "Editor" settings.
Unfortunately, this cut some on the width of the web pages embedded with the inline gate code.

Could you look into it please ? 

I think it's not all website. I'm having the issue with Gmail
Adding a - responsive ou - width option in advanced gate options might help avoid this?

Best,
Diane

**Comment by nguyenvanduocit** [comment]
In this case, please use `zoomFactor: 0.4` or less to zoom out the page.
