### ISSUE TITLE
Does not update (android 11)

### ISSUE THREAD

**Issue by merlinuwe** [nguyenvanduocit/obsidian-open-gate#65]
The plugin does not update. (At your website is no newer release available.)

But it shows:

1.11.1 -> 1.21.2

**Comment by nguyenvanduocit** [comment]
Thanks for your feedback, the last build was failed, i will update it in about next 5hrs

**Comment by nguyenvanduocit** [comment]
It should be updated

**Comment by merlinuwe** [comment]
For me, it does not install anymore under android 11.

**Comment by nguyenvanduocit** [comment]
Can you try again, I just update the release script, if still not, please DM me twitter or discord: https://discord.gg/MnRTYSPBrq

**Comment by merlinuwe** [comment]
Thank you very much, I'm on 1.11.6, now. ;-)
