### ISSUE TITLE
Failed to install 1.11.5

### ISSUE THREAD

**Issue by TVProduction** [nguyenvanduocit/obsidian-open-gate#66]
Attempting to update to the latest this morning and got a 'Failed to install...' error.

Used BRAT and got the following message:   This release is not complete and cannot be downloaded.  main.js is missing from the Release.
![image](https://github.com/nguyenvanduocit/obsidian-open-gate/assets/80490181/09328624-8397-4c6b-8fed-fb9206c26d0d)

One of the great plugins, and I really appreciate your work.

**Comment by nguyenvanduocit** [comment]
Thank you for your feedback. I just fixed a wrong release script for the new document site I developed in the past few days. You should be able to update now. By the way, please check out our new doc site here: https://open-gate.aiocean.io/

**Comment by TVProduction** [comment]
Installed perfectly.  Inline embedded view is the killer feature!
