### ISSUE TITLE
How to Refresh iframe Cache

### ISSUE THREAD

**Issue by erauner12** [nguyenvanduocit/obsidian-open-gate#68]
I'm experiencing an issue logging into one of the sites. The desktop version works correctly, but the mobile version does not. I believe resetting the cache on the mobile device may resolve the problem, but I'm unsure of the steps to do so.

Do you have any recommendations on how to address this?

**Comment by nguyenvanduocit** [comment]
Due to limitation of Obsidian on mobile, we use two different technology in desktop and mobile. On mobile, not every website works, especially websites that require cookies to support login/account. I think there are no easy ways to fix that.
