### ISSUE TITLE
Submitted support request on 5/2

### ISSUE THREAD

**Issue by angiioh** [nguyenvanduocit/obsidian-open-gate#70]
Hi! I'm sorry for posting this here, but I wasn't sure where else to put it. I filled out the online support form powered by Jira on 5/2 and have not heard back. I tried joining the discord, but the invite links have all expired. My inquiry was about assigning lucide icons to my gates. My icons were not displaying and I requested some guidance.

Thanks!

**Comment by nguyenvanduocit** [comment]
the issue was resolved, you just need to remove attributes width and height
