### ISSUE TITLE
Hello! Server resources of some Japanese websites, such as images and videos, cannot be parsed. . . 

### ISSUE THREAD

**Issue by zhouxinghong** [nguyenvanduocit/obsidian-open-gate#8]
Hello! This extension is well designed! 👍😜
However, server resources of some Japanese websites, such as images and videos, cannot be parsed. . . Hope that can improve it. . . Thanks!
OS: Win10
Version: 1.2.21
OBS: 1.1.16

**Comment by nguyenvanduocit** [comment]
I just released new version, Can you upgrade it and see if the issue still happen? If it still, please show me you console log by:

1. click on menu view > Toggle Developer Tools
2. Copy anything you see, like this:

![image](https://user-images.githubusercontent.com/1256953/224299435-4a52c38d-c247-4a72-a014-e1dfe16a0462.png)

**Comment by zhouxinghong** [comment]
> I just released new version, Can you upgrade it and see if the issue still happen? If it still, please show me you console log by:
> 
> 1. click on menu view > Toggle Developer Tools
> 2. Copy anything you see, like this:
> 
> ![image](https://user-images.githubusercontent.com/1256953/224299435-4a52c38d-c247-4a72-a014-e1dfe16a0462.png)

Hello! What this extension does is awesome! 👍😜 According to your tips, the previous problem no longer occurs after upgrading to the latest version. However, the slow speed of creating and opening website information may require further optimization of the code and improvement of website access performance. Thank you so much! 👍✌.

So I thought of an enhancement. It would be perfect if this extension could be paired with an effective ad blocking extension. 😜

**Comment by zhouxinghong** [comment]
Hello! Discovering a new problem, some Japanese websites can correctly open the website information in Chrome or Edge browser, but using this extension in obsidian can not be opened, but the following prompts can be displayed:
![2023-03-10_195656](https://user-images.githubusercontent.com/54253524/224534380-0097d859-be39-49fe-bbd3-68e4e447d135.png)
After many repeated experiments, the same Japanese website can correctly open the website information in Chrome or Edge browser. Essence Essence I hope you can check it out to see which functions are not perfect or stable. Essence Essence Thank you so much! 👍👍👍😜

**Comment by nguyenvanduocit** [comment]
In this case, did you try to set User Agent?

**Comment by zhouxinghong** [comment]
> In this case, did you try to set User Agent?

Hello! I just visited the website in the system proxy mode set by the user. The strange thing is that I can successfully access the website information in Chrome or Edge browsers, but I cannot succeed after creating a link through the open-link-with extension in Obsidian Notes. After accessing the information of this website, the website gives the above-mentioned response information.

**Comment by nguyenvanduocit** [comment]
The proxy you are using is install on browser(extension) or install on OS	(like apps)

**Comment by zhouxinghong** [comment]
The proxy tool I use is installed on the operating system

**Comment by nguyenvanduocit** [comment]
Sorry for the issue, I still can not reproduce and I don't really know how Obsidian use proxy. I still trying

**Comment by zhouxinghong** [comment]
Thank you so much for your efforts! I'll keep an eye out for recurrences of this issue. 👍😜

**Comment by zhouxinghong** [comment]
Hello! I just found a problem. When I switch to the dark theme, the shape and background color of the scroll bar are inconsistent with the background color of the theme. I hope you can improve this problem to be consistent with the background color of the theme, then it will be great! Thank you so much! 😜👍
![滚动条颜色](https://user-images.githubusercontent.com/54253524/227948555-db043961-cf60-432d-951b-2013f3dc2c54.png)

**Comment by zhouxinghong** [comment]
Hello! Found a problem that can be improved, the ideal performance is: add another shortcut key to display the list of already created websites, trigger this shortcut key to display the list of already created websites and allow users to use the mouse to select or use the up and down shortcut keys to list Select the website in the menu, and then open the selected website by triggering the Enter key to request access. A similar effect is as follows:

https://user-images.githubusercontent.com/54253524/228094448-2139a587-185c-4c15-84ff-f911d5af74ea.mp4

The advantage of this is that there is no need to set a corresponding shortcut key for each created website. 😜

Windows 10
The latest version

**Comment by nguyenvanduocit** [comment]
Totally agree. I will ship it now.

**Comment by zhouxinghong** [comment]
However, the style and height of the list should be optimized. Currently there is only one URL information, but the list seems too high. . . 😜👍

**Comment by zhouxinghong** [comment]
Ways to request to open the website:
2. Allow the user to use the up and down shortcut keys to select a website in the list, and then press the Enter key to open the selected website to request access.
The second mode of operation does not work. . .

**Comment by nguyenvanduocit** [comment]
Not implement yet, :D

**Comment by nguyenvanduocit** [comment]
Btw, I gonna close this issue. Please use discussions: https://github.com/nguyenvanduocit/obsidian-open-gate/discussions
