### ISSUE TITLE
Unable to load in Mobile

### ISSUE THREAD

**Issue by probabilityzero** [nguyenvanduocit/obsidian-open-gate#83]
I think this may be a problem in mobile and tab from obsidian itself, but is there a way around it? 

![Screenshot_2024-10-25-04-58-16-78_51606159b24eff83e24a54116878fe3e.jpg](https://github.com/user-attachments/assets/5bf1b4d2-8742-427b-8701-2a710cb47795)

**Comment by nguyenvanduocit** [comment]
On modile, we use just iframe, and look like some website blocked it self from being loaded in side an iframe. Technically, there are nothing to to with this.
